import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { Badge } from "@/components/ui/badge";
import { useDocumentTitle } from "@/hooks/use-document-title";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-8">
      <h2 className="font-serif text-lg tracking-tight mb-3">{title}</h2>
      <div className="space-y-3 text-sm text-muted-foreground leading-relaxed">
        {children}
      </div>
    </div>
  );
}

export default function TermsPage() {
  useDocumentTitle("Terms of Service");
  return (
    <div className="flex min-h-screen flex-col">
      <Header />

      <main className="flex-1">
        <div className="mx-auto max-w-2xl px-4 sm:px-6 py-14 sm:py-20">
          <Badge variant="outline" className="text-[10px] mb-5">
            Legal
          </Badge>
          <h1 className="font-serif text-2xl sm:text-3xl tracking-tight mb-2">
            Terms of Service
          </h1>
          <p className="text-xs text-muted-foreground mb-10">
            Last updated: 14 April 2026 · LuxProperty AI Ltd
          </p>

          <Section title="1. Acceptance of terms">
            <p>
              By accessing or using LuxProperty.ai (the "Service"), you agree to be bound by
              these Terms of Service ("Terms"). If you do not agree to these Terms, do not use
              the Service.
            </p>
            <p>
              The Service is operated by <strong className="text-foreground">LuxProperty AI Ltd</strong>, a company
              registered in England and Wales.
            </p>
          </Section>

          <Section title="2. Description of service">
            <p>
              LuxProperty.ai provides AI-assisted property intelligence briefs based on
              publicly available data from HM Land Registry and Postcodes.io. The Service
              is provided for informational purposes only.
            </p>
            <p>
              The Service includes free and paid subscription tiers. Features available on
              each tier are as described on the pricing page and may be updated from time to
              time.
            </p>
          </Section>

          <Section title="3. Important disclaimer — not professional advice">
            <p>
              <strong className="text-foreground">
                LuxProperty.ai reports are for informational purposes only and do not
                constitute professional property, financial, legal, or investment advice.
              </strong>
            </p>
            <p>
              You should not rely solely on any report generated by LuxProperty.ai when making
              a decision to buy, sell, or invest in property. We strongly recommend you seek
              independent professional advice from a qualified surveyor, solicitor, and/or
              financial adviser before making any property transaction.
            </p>
            <p>
              All data is sourced from HM Land Registry and Postcodes.io. While we make
              reasonable efforts to ensure accuracy, we cannot guarantee that data is
              complete, up-to-date, or free from errors. Historical price data covers
              registered transactions in England and Wales only. Scotland and Northern
              Ireland are not covered.
            </p>
          </Section>

          <Section title="4. Use of the service">
            <p>You agree to use the Service only for lawful purposes. You must not:</p>
            <ul className="list-disc pl-5 space-y-1.5">
              <li>Use the Service in any way that violates applicable laws or regulations</li>
              <li>Attempt to reverse engineer, scrape, or systematically extract data from the Service</li>
              <li>Resell, redistribute, or sublicense access to the Service without our written consent</li>
              <li>Use the Service to generate content intended to mislead or defraud third parties</li>
              <li>Attempt to gain unauthorised access to any part of the Service</li>
            </ul>
          </Section>

          <Section title="5. Subscriptions and payments">
            <p>
              Paid subscriptions are billed monthly (or annually if applicable) in advance.
              Subscription fees are non-refundable except as required by applicable law
              (including the Consumer Rights Act 2015 and applicable distance selling
              regulations).
            </p>
            <p>
              You may cancel your subscription at any time. Cancellation takes effect at the
              end of the current billing period. You will continue to have access to paid
              features until the end of the period for which you have paid.
            </p>
            <p>
              Payments are processed by Stripe. By subscribing, you also agree to Stripe's
              Terms of Service.
            </p>
            <p>
              We reserve the right to change subscription pricing with reasonable notice.
              We will notify existing subscribers at least 30 days before any price change
              takes effect.
            </p>
          </Section>

          <Section title="6. Intellectual property">
            <p>
              The LuxProperty.ai platform, including its design, code, and branding, is
              owned by LuxProperty AI Ltd. You may not copy, modify, or distribute any
              part of the platform without our written permission.
            </p>
            <p>
              Reports generated by LuxProperty.ai are provided for your personal or
              professional use. You may share reports with clients or third parties in the
              context of property transactions, provided you do not remove or obscure the
              LuxProperty.ai attribution.
            </p>
            <p>
              Underlying data is sourced from HM Land Registry (Crown copyright, Open
              Government Licence v3.0) and Postcodes.io (Open Government Licence). We do
              not claim ownership of this underlying data.
            </p>
          </Section>

          <Section title="7. Limitation of liability">
            <p>
              To the maximum extent permitted by applicable law, LuxProperty AI Ltd shall
              not be liable for:
            </p>
            <ul className="list-disc pl-5 space-y-1.5">
              <li>Any loss or damage arising from your use of or reliance on reports generated by the Service</li>
              <li>Any financial loss resulting from property transactions made in reliance on our data</li>
              <li>Inaccuracies, gaps, or errors in the underlying data from HM Land Registry or Postcodes.io</li>
              <li>Service interruptions, downtime, or data loss</li>
              <li>Any indirect, consequential, or special damages</li>
            </ul>
            <p>
              Nothing in these Terms limits our liability for death or personal injury caused
              by negligence, or for fraud or fraudulent misrepresentation.
            </p>
          </Section>

          <Section title="8. Governing law">
            <p>
              These Terms are governed by the laws of England and Wales. Any disputes
              arising from or in connection with these Terms shall be subject to the
              exclusive jurisdiction of the courts of England and Wales.
            </p>
          </Section>

          <Section title="9. Changes to these terms">
            <p>
              We may update these Terms from time to time. We will notify users of material
              changes by updating the "last updated" date at the top of this page.
              Continued use of the Service after changes constitutes acceptance of the
              updated Terms.
            </p>
          </Section>

          <Section title="10. Contact">
            <p>
              For questions about these Terms:{" "}
              <a href="mailto:legal@luxproperty.ai" className="text-primary underline-offset-2 hover:underline">
                legal@luxproperty.ai
              </a>
            </p>
            <p>
              LuxProperty AI Ltd<br />
              
              Registered in England and Wales
            </p>
          </Section>
        </div>
      </main>

      <Footer />
    </div>
  );
}
